#!/usr/bin/env node
/**
 * 把 locales/*.json 生成成一个可被打包器内联的 TS 模块。
 *
 * 为什么需要这一步：这个前端是**静态导出**的（`output: "export"`，随 wheel 分发），
 * 运行时没有服务端、也没法扫目录——语言清单必须在**构建时**烤进包里。
 *
 * ⛔ 生成物 `lib/locales.generated.ts` **入库**，不 gitignore。
 *    看起来反直觉，理由是失败方式：
 *      · 不入库 → 靠 npm 的 pre 钩子生成。而 `npm run build:static`（打 wheel 走的正是它）
 *        **不会**触发 `prebuild`（npm 只认同名的 `prebuild:static`），CI 的 typecheck 也跑在
 *        build 之前 —— 漏掉的路径会**静默**发出一个词条过时/缺失的包。
 *      · 入库 + CI 跑一遍生成器比对差异 → 过时就是 **CI 红**。
 *    这个仓已经吃过两次「静默用旧产物」的亏（v1.1 网页过时、ROADMAP R7 的构建时间戳），
 *    所以这里选**吵闹的失败**。
 *
 * Generates a bundler-inlinable TS module from locales/*.json.
 * The generated file is committed on purpose: the alternative fails silently, this fails loudly.
 */
import fs from "node:fs";
import path from "node:path";

const HERE = path.dirname(new URL(import.meta.url).pathname);
const FRONTEND = path.resolve(HERE, "..");
const LOCALES_DIR = path.join(FRONTEND, "locales");
const OUT = path.join(FRONTEND, "lib", "locales.generated.ts");

/** 正典语言：词条的 key 就是这门语言的原文，所以它的 strings 是恒等映射。
 *  它同时是**唯一的**语言字面量（域常量），别再往代码里加第二个。 */
const SOURCE_LANG = "en";

const files = fs.readdirSync(LOCALES_DIR).filter((f) => f.endsWith(".json")).sort();
if (!files.length) throw new Error(`${LOCALES_DIR} 里一个词条文件都没有`);

const locales = [];
for (const file of files) {
  const code = path.basename(file, ".json");
  const raw = JSON.parse(fs.readFileSync(path.join(LOCALES_DIR, file), "utf8"));

  // 结构校验放在生成时而不是运行时：坏文件应该让构建失败，而不是让界面在用户面前塌掉。
  const meta = raw.meta || {};
  for (const k of ["code", "label", "html"]) {
    if (typeof meta[k] !== "string" || !meta[k]) throw new Error(`${file}: meta.${k} 缺失或不是字符串`);
  }
  if (meta.code !== code) throw new Error(`${file}: meta.code=${meta.code} 与文件名对不上`);
  if (!raw.strings || typeof raw.strings !== "object") throw new Error(`${file}: strings 不是对象`);
  if (!Array.isArray(meta.match)) throw new Error(`${file}: meta.match 必须是数组（可以是空数组）`);

  locales.push({ meta, strings: raw.strings, count: Object.keys(raw.strings).length });
}

if (!locales.some((l) => l.meta.code === SOURCE_LANG)) {
  throw new Error(`正典语言 ${SOURCE_LANG} 没有词条文件——它同时是合法 key 的登记表，必须存在`);
}

const banner = `// ⚠️ 自动生成，别手改。改词条请改 locales/*.json，然后跑 \`npm run gen:locales\`。
// Generated by scripts/gen-locales.mjs — edit locales/*.json instead.
`;

const body = `${banner}
export type LocaleMeta = {
  /** 语言代码，同文件名 */
  code: string;
  /** 用它**自己的语言**写的名字，切换菜单里显示 */
  label: string;
  /** 给 <html lang> 用的标签 */
  html: string;
  /** navigator.language 的前缀，首次访问据此自动选 */
  match: string[];
};

export type Locale = { meta: LocaleMeta; strings: Record<string, string> };

/** 正典语言：词条 key 就是它的原文。**代码里唯一的语言字面量。** */
export const SOURCE_LANG = ${JSON.stringify(SOURCE_LANG)};

/** 全部可用语言，由 locales/ 目录扫描得出——代码里没有语言清单。 */
export const LOCALES: Record<string, Locale> = ${JSON.stringify(
  Object.fromEntries(locales.map((l) => [l.meta.code, { meta: l.meta, strings: l.strings }])),
  null,
  2,
)};
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.log(`locales → ${path.relative(FRONTEND, OUT)}`);
for (const l of locales) {
  const tag = l.meta.code === SOURCE_LANG ? "  (registry / 登记表)" : "";
  console.log(`  ${l.meta.code.padEnd(4)} ${String(l.count).padStart(4)} strings  ${l.meta.label}${tag}`);
}
